import Link from "next/link";

import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { getSansadDarpanWeeklyBriefs } from "@/lib/api";

export default async function SansadDarpanWeeklyBriefsPage() {
  const data = await getSansadDarpanWeeklyBriefs();
  const publishedBriefs = data.briefs.filter((b) => b.status === "published" || b.status === "draft");
  const latestBrief = publishedBriefs[0];

  return (
    <div className="page-shell product-shell" data-product="sansaddarpan">
      <SiteHeader active="sansaddarpan-weekly-briefs" product="sansaddarpan" />

      <main className="screen-main">
        <section className="screen-frame mandate-frame sansaddarpan-frame">
          <nav className="sansaddarpan-breadcrumbs" aria-label="Breadcrumb">
            <Link href="/">AgentSabha</Link>
            <span>/</span>
            <Link href="/sansaddarpan">SansadDarpan</Link>
            <span>/</span>
            <span aria-current="page">Weekly Briefs</span>
          </nav>

          <section className="sansaddarpan-dashboard-header">
            <div>
              <p className="eyebrow">WEEKLY CONSTITUENCY INTELLIGENCE BRIEFS</p>
              <h1 className="product-title">One constituency each week. AI research for the MP who could act.</h1>
              <p className="hero-body">
                Each brief is generated by AI from live welfare data, parliamentary records, and constituency evidence.
                The MP is framed as the hero who could act — never as the subject of judgment.
              </p>
            </div>
            <div className="sansaddarpan-dashboard-actions">
              {latestBrief ? (
                <Link className="secondary-button button-link" href={`/sansaddarpan/weekly-briefs/${latestBrief.id}`}>
                  Read latest brief
                </Link>
              ) : null}
              <Link className="outline-button button-link" href="/sansaddarpan/methodology">
                View methodology
              </Link>
            </div>
          </section>

          <section className="sansaddarpan-monitor-shell">
            <div className="sansaddarpan-monitor-topbar">
              <div className="sansaddarpan-monitor-identity">
                <div className="sansaddarpan-monitor-mark">WB</div>
                <div>
                  <div className="sansaddarpan-monitor-title">Weekly brief register</div>
                  <div className="sansaddarpan-monitor-sub">AI-generated constituency intelligence briefs with video scripts and MP summaries</div>
                </div>
              </div>
              <span className="sansaddarpan-monitor-pill">AI-generated public output</span>
              <div className="sansaddarpan-live-wrap">
                <span className="sansaddarpan-live-dot" aria-hidden="true"></span>
                <span className="sansaddarpan-live-label">Claude-powered</span>
              </div>
            </div>

            <div className="sansaddarpan-monitor-metrics">
              <article className="sansaddarpan-monitor-metric">
                <strong>{data.briefs.length}</strong>
                <span>Total briefs generated</span>
              </article>
              <article className="sansaddarpan-monitor-metric">
                <strong>{data.briefs.filter((b) => b.status === "published").length}</strong>
                <span>Published briefs</span>
              </article>
              <article className="sansaddarpan-monitor-metric">
                <strong>{data.briefs.filter((b) => b.status === "draft").length}</strong>
                <span>Draft briefs pending review</span>
              </article>
              <article className="sansaddarpan-monitor-metric">
                <strong>{new Set(data.briefs.map((b) => b.constituency_name)).size}</strong>
                <span>Constituencies covered</span>
              </article>
              <article className="sansaddarpan-monitor-metric">
                <strong>543</strong>
                <span>Total Lok Sabha constituencies</span>
              </article>
            </div>

            <div className="sansaddarpan-monitor-body">
              <div className="sansaddarpan-monitor-main">
                <div className="sansaddarpan-sec-label">Brief timeline</div>
                {data.briefs.length === 0 ? (
                  <div className="sansaddarpan-empty-state">
                    <strong>No briefs generated yet.</strong>
                    <p>Weekly briefs are generated via the internal API and appear here after creation. The pipeline rotates through 543 constituencies.</p>
                  </div>
                ) : null}
                {data.briefs.map((brief, index) => (
                  <Link key={brief.id} href={`/sansaddarpan/weekly-briefs/${brief.id}`} className="sansaddarpan-tl-item">
                    <div className="sansaddarpan-tl-label">W{brief.week_number}</div>
                    <div className="sansaddarpan-tl-dot-col">
                      <span className={`sansaddarpan-tl-dot ${brief.status === "published" ? "healthy" : "warning"}`}></span>
                      {index < data.briefs.length - 1 ? <span className="sansaddarpan-tl-line"></span> : null}
                    </div>
                    <div className="sansaddarpan-tl-card">
                      <div className="sansaddarpan-tl-title">{brief.headline}</div>
                      <div className="sansaddarpan-tl-body">
                        {brief.constituency_name}, {brief.constituency_state} · {brief.mp_name || "MP not mapped"}
                      </div>
                      <div className="sansaddarpan-tl-tags">
                        <span className="sansaddarpan-tag">Week {brief.week_number}, {brief.year}</span>
                        <span className="sansaddarpan-tag">{brief.status}</span>
                        {brief.youtube_title ? <span className="sansaddarpan-tag">Video ready</span> : null}
                      </div>
                    </div>
                  </Link>
                ))}
              </div>

              <aside className="sansaddarpan-monitor-side">
                <div className="sansaddarpan-sec-label">How briefs work</div>
                <div className="sansaddarpan-flag-list">
                  <div className="sansaddarpan-flag-item">
                    <span className="sansaddarpan-flag-icon published"></span>
                    <div>
                      <div className="sansaddarpan-flag-title">AI researches, humans verify</div>
                      <div className="sansaddarpan-flag-body">Each brief starts as a draft. It is published only after review confirms the data sources and parliamentary actions are accurate.</div>
                    </div>
                  </div>
                  <div className="sansaddarpan-flag-item">
                    <span className="sansaddarpan-flag-icon review"></span>
                    <div>
                      <div className="sansaddarpan-flag-title">Three outputs per brief</div>
                      <div className="sansaddarpan-flag-body">A public intelligence brief, a YouTube/Instagram video script, and a one-page WhatsApp-ready MP summary.</div>
                    </div>
                  </div>
                  <div className="sansaddarpan-flag-item">
                    <span className="sansaddarpan-flag-icon archived"></span>
                    <div>
                      <div className="sansaddarpan-flag-title">Bilingual by default</div>
                      <div className="sansaddarpan-flag-body">Every brief includes English primary content and Hindi translations for key sections.</div>
                    </div>
                  </div>
                </div>
              </aside>
            </div>
          </section>

          {data.briefs.length > 0 ? (
            <section className="frame-panel full-width-panel sansaddarpan-surface">
              <div className="section-heading compact-heading">
                <div>
                  <p>Published briefs</p>
                  <h2>Constituency intelligence cards</h2>
                </div>
              </div>
              <div className="sansaddarpan-module-grid">
                {data.briefs.map((brief) => (
                  <article key={brief.id} className="summary-tile sansaddarpan-card">
                    <div className="sansaddarpan-case-header">
                      <span className="summary-kicker">Week {brief.week_number}, {brief.year}</span>
                      <span className={`sansaddarpan-status-pill ${brief.status === "published" ? "published" : "review"}`}>
                        {brief.status}
                      </span>
                    </div>
                    <h3>{brief.constituency_name}, {brief.constituency_state}</h3>
                    <p>{brief.headline}</p>
                    <div className="sansaddarpan-metric-row">
                      <strong>{brief.mp_name || "MP"}</strong>
                      <span>{brief.youtube_title ? "Video script ready" : "Brief only"}</span>
                    </div>
                    <Link className="secondary-button forum-open-link" href={`/sansaddarpan/weekly-briefs/${brief.id}`}>
                      Open brief
                    </Link>
                  </article>
                ))}
              </div>
            </section>
          ) : null}
        </section>
      </main>

      <SiteFooter brand="SansadDarpan" note="Weekly constituency intelligence briefs powered by AI research" endLabel="AI-generated public output" />
    </div>
  );
}
